### ISSUE TITLE
Need New Keys for End Point API Auctions List

### ISSUE THREAD

**Issue by mrhandoko** [BukaLelang/bukalelang-backend#2]
I need more two key for this end point http://api.bukalelang.id/auctions

> HTTP/1.1 200 OK
[{
  "success": true,
  "message": 'Success load list of auctions',
  "auctions": [
        {
         id: 23,
         productId: '31fsa21',
         image: url, <-- Add this
         title: 'Tamiya super cepat',
         category: 'Mainan',
         new: false,
         weight: 1000,
         description: 'Tamiya ini di rakit oleh ahli fisika, dengan memperhatikan dengan seksama gaya gesek dan kelembaman sehigga mengurangi kaya gesek dengan lintasan membuanya super cepat.',
         min_price: 200000,
         max_price: 3000000,
         current_price: 600000,
         kelipatan_bid: 20000,
         running: true/false, <-- Add this
         start_date: '2017-04-16T18:22:54.846+07:00',
         end_date: '2017-05-16T18:22:54.846+07:00'
       }
     ]
}]

**Comment by dikyarga** [comment]
Done!

Thanks for reporting (:
